### ISSUE TITLE
8690.1 DEV Add new fields maxNodeIdleTimeInHrs and maxNodeIdleTimeOverridden to subscriptions schema

### ISSUE THREAD

**Issue by ankul-shippable** [Shippable/admiral#1008]
https://github.com/Shippable/pm/issues/8690

```
maxNodeIdleTimeInHrs:
  type: INTEGER
  allowNull: true

maxNodeIdleTimeOverridden: 
  type: BOOLEAN
  allowNull: true
```
